import Head from 'next/head'
import { Inter } from 'next/font/google'
import 'tachyons';
import Input from '../components/input';
import Title from '../components/title';
import Footer from '../components/footer';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>QR Code Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <section className="pa2 whole-body flex flex-column">
          <div className='w-100 container mb4 flex flex-column justify-between'>
            <div className='w-50 flex'>
              <Title />
            </div>
            <div className='w-50'>
              <Input />
            </div>
          </div>
          <Footer />
        </section>
        )

      </main>
    </>
  )
}
